root = "."
tmp_dir = "tmp"

[build]
    bin = "./tmp/main"
    cmd = "go run ."
    delay = 1000
    stop_on_error = true

[log]
    time = true
    color = true

[misc]
    clean_on_exit = true

[watch]
    dir = ["./cmd", "./internal", "./templates"]